from xml.sax.saxutils import escape

lines_top = [
    "INTERSTATE TRADE COMPANY LIMITED",
    "Email: sales@interstatetrade.net",
    "Mombasa Branch, Ganjon, Mombasa, Kenya",
    "Web: www.interstatetrade.net",
    "",
    "CUSTOMER NAME:       Jagjit Singh",
    "ACCOUNT REF:         HIC-MBS-CON-2024-HBG",
    "CONSIGNMENT NO:      HBG0001-Alexander B",
    "CONSIGNMENT CHANNEL: 0722601996 (Director’s Trade Line)",
    "",
    "         CONSIGNMENT SALES ACCOUNT STATEMENT",
    "",
    "STATEMENT DATE: 25-Mar-2026",
    "REPORT PERIOD: Jan 2024 – July 2024",
    "",
    "DATE       TIME      TRANSACTION REF   DESCRIPTION                         DEBIT (Kshs)   CREDIT (Kshs)   BALANCE (Kshs)",
    "-------------------------------------------------------------------------------------------------------------------------",
]

rows = [
"24-Jan-24  -         -                 Stock Issue: 2 truck batteries       60,000.00       -               60,000.00",
"24-Jan-24  -         -                 Stock Issue: Electric compressor      80,000.00       -              140,000.00",
"24-Jan-24  -         -                 Stock Issue: Portable generator       60,000.00       -              200,000.00",
"24-Jan-24  -         -                 Stock Issue: Vertical band saw        50,000.00       -              250,000.00",
"",
"14-Feb-24  10:26:47  QJE4UUVMTU        M-Pesa Payment Received               -             100,000.00      150,000.00",
"16-Feb-24  15:06:59  QJG311C3AB        M-Pesa Payment Received               -              73,000.00       77,000.00",
"16-Feb-24  17:27:33  QJG61CYET6        M-Pesa Payment Received               -               7,000.00       70,000.00",
"16-Feb-24  21:39:10  QJG520WBNZ        M-Pesa Payment Received               -              30,000.00       40,000.00",
"18-Feb-24  23:24:59  QJI661Y30K        M-Pesa Payment Received               -              30,000.00       10,000.00",
"",
"04-Feb-24  20:01:17  RB47WRCSJ9        Funds Transferred to (credit)      2,000.00         -               12,000.00",
"07-Feb-24  20:41:24  RB785TORM6        Funds Transferred to (credit)      1,300.00         -               13,300.00",
"08-Feb-24  20:03:16  RB878AUNKB        Funds Transferred to (credit)      2,000.00         -               15,300.00",
"",
"-------------------------------------------------------------------------------------------------------------------------",
"TOTAL INVENTORY VALUE ISSUED:        Kshs 250,000.00",
"TOTAL TRADE REMITTANCES RECEIVED:    Kshs 270,000.00",
"TOTAL FUNDS TRANSFERRED (CREDIT):    Kshs 5,300.00",
"OUTSTANDING TRADE BALANCE:           Kshs 15,300.00",
"",
"DECLARATION:",
"This document is a computer-generated extract of the sales account records.",
"It represents recovery of funds from stock sales as detailed above.",
"This does not represent a personal loan or liability.",
"",
"Generated by: System Admin [Inventory Control – Ganjoni Branch]",
]

svg = []
svg.append('<svg xmlns="http://www.w3.org/2000/svg" width="1800" height="1300" viewBox="0 0 1800 1300">')
svg.append('<rect width="1800" height="1300" fill="#8f5f49"/>')
svg.append('<g transform="translate(180 150) rotate(-4)">')
svg.append('<rect x="0" y="0" width="1450" height="1020" fill="white"/>')
svg.append('<rect x="38" y="38" width="1374" height="944" fill="none" stroke="#666" stroke-width="2" stroke-dasharray="12 8"/>')

y = 88
for t in lines_top:
    svg.append(f'<text x="72" y="{y}" font-family="monospace" font-size="22" fill="#111">{escape(t)}</text>')
    y += 33

for t in rows:
    svg.append(f'<text x="72" y="{y}" font-family="monospace" font-size="18" fill="#111">{escape(t)}</text>')
    y += 27

svg.append('<rect x="960" y="780" width="410" height="150" fill="none" stroke="#315a9a" stroke-width="4"/>')
svg.append('<text x="976" y="820" font-family="monospace" font-size="26" fill="#315a9a">INTERSTATE TRADE COMPANY</text>')
svg.append('<text x="976" y="856" font-family="monospace" font-size="26" fill="#315a9a">RECEIVED</text>')
svg.append('<text x="976" y="892" font-family="monospace" font-size="26" fill="#315a9a">25-MAR-2026</text>')
svg.append('</g></svg>')

with open('statement_generated.svg', 'w', encoding='utf-8') as f:
    f.write('\n'.join(svg))

print('Generated statement_generated.svg')
